#!/bin/sh

. $PWD/_tasks/des_ops

fyl=NseFoExchDetails.conf
#old=$(cat $rdir/$cfgdir/$fyl | grep '@' | cut -d = -f 2 | head -n 1)
passwd=$(date +'%a')@$(date +'%m%d')

chPASSWD(){
	while IFS=, read ip str rdir cfgdir engine
	do
		ssh -n root@$ip "sed -i s/EMPTY/$passwd/g  $rdir/$cfgdir/$fyl" & disown
		sleep 2
	done<_path/server.csv
	wait
}
updatePASSWD(){
	chPASSWD
	sleep 1
	killDES;sleep 5;initDES;sleep 10;killDES
	while IFS=, read ip str rdir cfgdir engine
	do
		old=$(ssh -n root@$ip "cat $rdir/$cfgdir/$fyl | grep '@' | cut -d = -f 2 | head -n 1")
		echo $old
		ssh -n root@$ip "sed -i s/$passwd/EMPTY/g  $rdir/$cfgdir/$fyl" & disown
		ssh -n root@$ip  "sed -i s/$old/$passwd/g  $rdir/$cfgdir/$fyl" & disown
	done<_path/server.csv
}
